version: 2
updates:
  - package-ecosystem: "bundler"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Madrid"
    assignees:
      - "javierav"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Madrid"
    assignees:
      - "javierav"
